// Сід-дані для seed-demo.ts: знімок 15 тестових закладів «Пиячок» (джерело — OpenStreetMap,
// фото — Unsplash webp у repo seed-assets/venues/venue-NN). Власники — user1/user2/user3,
// пароль User1234. Слідкуй, щоб photos/mainPhotoIdx відповідали файлам у seed-assets.

export const SEED_TAGS = [
  {
    "slug": "cocktails",
    "name": "Коктейлі",
  },
  {
    "slug": "food",
    "name": "Кухня",
  },
  {
    "slug": "music",
    "name": "Жива музика",
  },
  {
    "slug": "dancing",
    "name": "Танцпол",
  },
  {
    "slug": "wine",
    "name": "Вино",
  },
  {
    "slug": "beer",
    "name": "Пиво",
  },
  {
    "slug": "dj",
    "name": "Діджеї",
  },
  {
    "slug": "sports",
    "name": "Трансляції спорту",
  },
  {
    "slug": "karaoke",
    "name": "Караоке",
  },
  {
    "slug": "billiards",
    "name": "Більярд",
  },
];

export const SEED_VENUES = [
  {
    "owner": "user1",
    "name": "Rafinad People",
    "description": "Нічний клуб Rafinad People у самому центрі Львова — танцювальний майданчик із резидентами та запрошеними діджеями, потужним звуком, світлом і лазером. Кілька барних стійок, VIP-зона, вечірки до ранку: заклад працює цілодобово.",
    "address": "м. Львів, вул. Степана Руданського, 1",
    "latitude": "49.838350",
    "longitude": "24.030760",
    "contacts": {
      "phone": "+380664000888",
      "website": "https://www.rafinad-club.com/",
    },
    "workingHours": {
      "fri": "24/7",
      "mon": "24/7",
      "sat": "24/7",
      "sun": "24/7",
      "thu": "24/7",
      "tue": "24/7",
      "wed": "24/7",
    },
    "averageCheck": 500.0,
    "type": "club",
    "features": [
      "wifi",
      "vip",
      "live_music",
    ],
    "tags": [
      "dancing",
      "dj",
      "cocktails",
    ],
    "photos": [
      "seed-assets/venues/venue-01/photo-1.webp",
      "seed-assets/venues/venue-01/photo-2.webp",
      "seed-assets/venues/venue-01/photo-3.webp",
      "seed-assets/venues/venue-01/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user1",
    "name": "Караоке-клуб «Паганіні»",
    "description": "Караоке-клуб «Паганіні» у Луцьку — професійний звук, тисячі пісень українською та англійською, сцена й окремі VIP-кабінети. Нічний формат: працює з 21:00 до ранку. Ідеально підходить для днів народження, корпоративів та вечірок з друзями.",
    "address": "м. Луцьк, вул. Електроапаратна, 4",
    "latitude": "50.740040",
    "longitude": "25.378320",
    "contacts": {
      "phone": "+380959317070",
      "website": "https://melodija.com.ua/karaoke-lutsk/",
    },
    "workingHours": {
      "fri": "21:00-05:00",
      "mon": "21:00-05:00",
      "sat": "21:00-05:00",
      "sun": "21:00-05:00",
      "thu": "21:00-05:00",
      "tue": "21:00-05:00",
      "wed": "21:00-05:00",
    },
    "averageCheck": 600.0,
    "type": "club",
    "features": [
      "live_music",
      "vip",
      "wifi",
    ],
    "tags": [
      "music",
      "karaoke",
      "dancing",
    ],
    "photos": [
      "seed-assets/venues/venue-02/photo-1.webp",
      "seed-assets/venues/venue-02/photo-2.webp",
      "seed-assets/venues/venue-02/photo-3.webp",
      "seed-assets/venues/venue-02/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user1",
    "name": "Оушен Бар",
    "description": "Оушен Бар у центрі Івано-Франківська — заклад з морською тематикою в декорі: широка барна карта з пивом та коктейлями, кухня з морепродуктами, трансляції матчів і легка тераса в літній сезон. Приходять на обід, вечірні зустрічі та нічні коктейлі.",
    "address": "м. Івано-Франківськ, вул. Страчених Націоналістів, 1",
    "latitude": "48.922210",
    "longitude": "24.711140",
    "contacts": {
      "phone": "+380685903030",
      "website": "https://oushen.choiceqr.com/",
      "instagram": "https://www.instagram.com/oushen_bar/",
    },
    "workingHours": {
      "fri": "11:00-23:00",
      "mon": "11:00-23:00",
      "sat": "11:00-23:00",
      "sun": "11:00-23:00",
      "thu": "11:00-23:00",
      "tue": "11:00-23:00",
      "wed": "11:00-23:00",
    },
    "averageCheck": 400.0,
    "type": "bar",
    "features": [
      "live_music",
      "wifi",
      "terrace",
    ],
    "tags": [
      "food",
      "cocktails",
    ],
    "photos": [
      "seed-assets/venues/venue-03/photo-1.webp",
      "seed-assets/venues/venue-03/photo-2.webp",
      "seed-assets/venues/venue-03/photo-3.webp",
      "seed-assets/venues/venue-03/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user1",
    "name": "Пʼяна Вишня (пл. Ринок, 11)",
    "description": "Винний монобар «Пʼяна Вишня» у самому серці Львова, на пл. Ринок, 11. Подають фірмову вишневу настоянку «Вишнівку» 17,5°, настояну на коньячному спирті та стиглих вишнях — розлиту або гарячку, а також солодкий корж «Пʼяна вишня». Затишний інтерʼєр, теплі світильники, кілька поверхів у стародавній камʼяниці. Ідеальне місце для зустрічі з друзями після прогулянки містом.",
    "address": "м. Львів, пл. Ринок, 11",
    "latitude": "49.842320",
    "longitude": "24.031460",
    "contacts": {
      "phone": "+380676742661",
      "website": "https://pianavyshnia.com",
      "instagram": "https://instagram.com/pianavyshnia",
    },
    "workingHours": {
      "fri": "10:00-02:00",
      "mon": "10:00-00:00",
      "sat": "10:00-02:00",
      "sun": "10:00-01:00",
      "thu": "10:00-00:00",
      "tue": "10:00-00:00",
      "wed": "10:00-00:00",
    },
    "averageCheck": 200.0,
    "type": "bar",
    "features": [
      "wifi",
      "terrace",
    ],
    "tags": [
      "cocktails",
      "wine",
    ],
    "photos": [
      "seed-assets/venues/venue-04/photo-1.webp",
      "seed-assets/venues/venue-04/photo-2.webp",
      "seed-assets/venues/venue-04/photo-3.webp",
      "seed-assets/venues/venue-04/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user1",
    "name": "Спорт-бар «10 дерунів»",
    "description": "Спорт-бар «10 дерунів» у Луцьку — великі екрани з трансляціями футбольних матчів і турнірів, розлите пиво та плотна класична кухня. Затишний зал з барною стійкою, гучна атмосфера на ключових матчах і дружні компанії до пізньої ночі.",
    "address": "м. Луцьк, вул. Івана Корсака, 40-А",
    "latitude": "50.782300",
    "longitude": "25.368260",
    "contacts": {
      "website": "https://adrenalin.lutsk.ua/restoratsiya/sportivniy-bar-10-deruniv/",
    },
    "workingHours": {
      "fri": "11:00-02:00",
      "mon": "11:00-23:00",
      "sat": "11:00-02:00",
      "sun": "11:00-22:00",
      "thu": "11:00-23:00",
      "tue": "11:00-23:00",
      "wed": "11:00-23:00",
    },
    "averageCheck": 350.0,
    "type": "bar",
    "features": [
      "wifi",
      "live_music",
      "parking",
    ],
    "tags": [
      "sports",
      "food",
      "beer",
    ],
    "photos": [
      "seed-assets/venues/venue-05/photo-1.webp",
      "seed-assets/venues/venue-05/photo-2.webp",
      "seed-assets/venues/venue-05/photo-3.webp",
      "seed-assets/venues/venue-05/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user2",
    "name": "Бар «Богеміус»",
    "description": "Бар «Богеміус» у Старому місті Чернівців — вечірній заклад з винною картою, коктейлями та живою музикою. Тепла атмосфера старих стін, довга барна стійка, довгі суботні ночі. Гучні компанії, романтичні побачення та винні вечори.",
    "address": "м. Чернівці, вул. Головна, 58",
    "latitude": "48.288050",
    "longitude": "25.934840",
    "contacts": {
      "phone": "+380372529847",
    },
    "workingHours": {
      "fri": "10:00-02:00",
      "mon": "10:00-02:00",
      "sat": "10:00-02:00",
      "sun": "10:00-02:00",
      "thu": "10:00-02:00",
      "tue": "10:00-02:00",
      "wed": "10:00-02:00",
    },
    "averageCheck": 300.0,
    "type": "bar",
    "features": [
      "live_music",
      "wifi",
    ],
    "tags": [
      "wine",
      "cocktails",
      "music",
    ],
    "photos": [
      "seed-assets/venues/venue-06/photo-1.webp",
      "seed-assets/venues/venue-06/photo-2.webp",
      "seed-assets/venues/venue-06/photo-3.webp",
      "seed-assets/venues/venue-06/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user2",
    "name": "Нічний клуб «Аладін»",
    "description": "Нічний клуб «Аладін» у центрі Рівного — танцпол із сучасним звуком і світлом, гостьові діджеї та тематичні вечірки вихідного дня. Лаунж-зона з баром для спокійніших вечорів, у літній сезон — веранда. Нічний формат: до самого ранку у пʼятницю та суботу.",
    "address": "м. Рівне, вул. Поштова, 11",
    "latitude": "50.621000",
    "longitude": "26.250080",
    "contacts": {},
    "workingHours": {
      "fri": "20:00-05:00",
      "mon": "20:00-03:00",
      "sat": "20:00-05:00",
      "sun": "20:00-02:00",
      "thu": "20:00-04:00",
      "tue": "20:00-03:00",
      "wed": "20:00-03:00",
    },
    "averageCheck": 400.0,
    "type": "club",
    "features": [
      "vip",
      "wifi",
    ],
    "tags": [
      "dancing",
      "dj",
      "cocktails",
    ],
    "photos": [
      "seed-assets/venues/venue-07/photo-1.webp",
      "seed-assets/venues/venue-07/photo-2.webp",
      "seed-assets/venues/venue-07/photo-3.webp",
      "seed-assets/venues/venue-07/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user2",
    "name": "Нічний клуб «Алюр»",
    "description": "Нічний клуб «Алюр» на просп. Злуки у Тернополі — танцювальний майданчик із сучасним звуком та світлом, резидентами й запрошеними діджеями та тематичними вечірками вихідного дня. Головний танцпол + лаунж-зона з баром, VIP-кабінети для компаній.",
    "address": "м. Тернопіль, просп. Злуки, 45",
    "latitude": "49.558100",
    "longitude": "25.632930",
    "contacts": {
      "website": "https://allureclub.com.ua/",
    },
    "workingHours": {
      "fri": "21:00-06:00",
      "mon": "21:00-04:00",
      "sat": "21:00-06:00",
      "sun": "21:00-03:00",
      "thu": "21:00-06:00",
      "tue": "21:00-04:00",
      "wed": "21:00-04:00",
    },
    "averageCheck": 450.0,
    "type": "club",
    "features": [
      "vip",
      "wifi",
      "live_music",
    ],
    "tags": [
      "dancing",
      "cocktails",
      "dj",
    ],
    "photos": [
      "seed-assets/venues/venue-08/photo-1.webp",
      "seed-assets/venues/venue-08/photo-2.webp",
      "seed-assets/venues/venue-08/photo-3.webp",
      "seed-assets/venues/venue-08/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user2",
    "name": "Паб 34",
    "description": "Паб 34 на головній вулиці Чернівців — класичний формат пабу: довга барна стійка, широке пивне меню, сидр з бочок, кухня гриль і трансляції спортивних матчів. Пізньої пʼятниці та суботи — музика до ночі. Місце зустрічі друзів та студентів міста.",
    "address": "м. Чернівці, вул. Головна, 34",
    "latitude": "48.290970",
    "longitude": "25.934730",
    "contacts": {
      "phone": "+380953343434",
      "website": "https://www.pub34.com/",
    },
    "workingHours": {
      "fri": "11:00-02:00",
      "mon": "11:00-00:00",
      "sat": "11:00-02:00",
      "sun": "12:00-23:00",
      "thu": "11:00-00:00",
      "tue": "11:00-00:00",
      "wed": "11:00-00:00",
    },
    "averageCheck": 300.0,
    "type": "bar",
    "features": [
      "live_music",
      "wifi",
      "parking",
    ],
    "tags": [
      "sports",
      "beer",
      "music",
    ],
    "photos": [
      "seed-assets/venues/venue-09/photo-1.webp",
      "seed-assets/venues/venue-09/photo-2.webp",
      "seed-assets/venues/venue-09/photo-3.webp",
      "seed-assets/venues/venue-09/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user2",
    "name": "Ресторан-бар «Ной»",
    "description": "Ресторан-бар «Ной» у центрі Тернополя — просторий зал на 120 місць, європейська та авторська кухня, широке винне меню й коктейлі. Тепле світло, жива атмосфера вечорів; доречно як для бізнес-обідів, так і для сімейних свят та зустрічей з друзями.",
    "address": "м. Тернопіль, вул. Торгиця, 31",
    "latitude": "49.545160",
    "longitude": "25.595180",
    "contacts": {
      "phone": "+380352255628",
    },
    "workingHours": {
      "fri": "11:00-02:00",
      "mon": "11:00-02:00",
      "sat": "11:00-02:00",
      "sun": "11:00-02:00",
      "thu": "11:00-02:00",
      "tue": "11:00-02:00",
      "wed": "11:00-02:00",
    },
    "averageCheck": 400.0,
    "type": "bar",
    "features": [
      "terrace",
      "wifi",
      "parking",
    ],
    "tags": [
      "wine",
      "food",
    ],
    "photos": [
      "seed-assets/venues/venue-10/photo-1.webp",
      "seed-assets/venues/venue-10/photo-2.webp",
      "seed-assets/venues/venue-10/photo-3.webp",
      "seed-assets/venues/venue-10/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user3",
    "name": "EscoBar",
    "description": "EscoBar у Старе Міті Житомира — вечірній бар з коктейлями та повноценною кухнею: бургери, закуски на компанію. Вечори з музикою та гучні суботи; затишний зал з барною стійкою для великих компаній і днів народження.",
    "address": "м. Житомир, вул. Велика Бердичівська, 6",
    "latitude": "50.253660",
    "longitude": "28.662730",
    "contacts": {
      "instagram": "https://www.instagram.com/escobar.zt/",
    },
    "workingHours": {
      "fri": "12:00-02:00",
      "mon": "12:00-00:00",
      "sat": "12:00-02:00",
      "sun": "12:00-23:00",
      "thu": "12:00-01:00",
      "tue": "12:00-00:00",
      "wed": "12:00-00:00",
    },
    "averageCheck": 350.0,
    "type": "bar",
    "features": [
      "wifi",
      "live_music",
    ],
    "tags": [
      "music",
      "cocktails",
      "food",
    ],
    "photos": [
      "seed-assets/venues/venue-11/photo-1.webp",
      "seed-assets/venues/venue-11/photo-2.webp",
      "seed-assets/venues/venue-11/photo-3.webp",
      "seed-assets/venues/venue-11/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user3",
    "name": "Бар «Молодість»",
    "description": "Бар-ресторан «Молодість» у київських Хрестах — легендарна локація, культовий заклад з винним та коктейльним меню, кухнею на грилі і літньою верандою. Днем — затишні обіди та кава, вечорами — вино, коктейлі й вечірки під світлом гірлянди.",
    "address": "м. Київ, вул. Князів Острозьких (Хрести)",
    "latitude": "50.442170",
    "longitude": "30.544600",
    "contacts": {
      "phone": "+380977041319",
      "facebook": "https://www.facebook.com/molodistkyiv/",
      "instagram": "https://www.instagram.com/molodistkyiv/",
    },
    "workingHours": {
      "fri": "12:00-23:00",
      "mon": "12:00-23:00",
      "sat": "12:00-23:00",
      "sun": "12:00-23:00",
      "thu": "12:00-23:00",
      "tue": "12:00-23:00",
      "wed": "12:00-23:00",
    },
    "averageCheck": 450.0,
    "type": "bar",
    "features": [
      "terrace",
      "wifi",
    ],
    "tags": [
      "wine",
      "food",
      "cocktails",
    ],
    "photos": [
      "seed-assets/venues/venue-12/photo-1.webp",
      "seed-assets/venues/venue-12/photo-2.webp",
      "seed-assets/venues/venue-12/photo-3.webp",
      "seed-assets/venues/venue-12/photo-4.webp",
      "seed-assets/venues/venue-12/photo-5.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user3",
    "name": "Бар «Тарантино»",
    "description": "Культовий бар «Тарантино» на Проскурівській у Хмельницькому — заклад у стилістиці фільмів Тарантіно: коктейлі, крафт-коктейльне меню, музика та вечірок атмосферa. Відкритий з 17:00 до ранку; улюблене місце вечірніх зустрічей міста.",
    "address": "м. Хмельницький, вул. Проскурівська, 83/1",
    "latitude": "49.420090",
    "longitude": "26.995390",
    "contacts": {
      "phone": "+380980313777",
    },
    "workingHours": {
      "fri": "17:00-05:00",
      "mon": "17:00-05:00",
      "sat": "17:00-05:00",
      "sun": "17:00-05:00",
      "thu": "17:00-05:00",
      "tue": "17:00-05:00",
      "wed": "17:00-05:00",
    },
    "averageCheck": 350.0,
    "type": "bar",
    "features": [
      "wifi",
      "live_music",
    ],
    "tags": [
      "beer",
      "music",
      "cocktails",
    ],
    "photos": [
      "seed-assets/venues/venue-13/photo-1.webp",
      "seed-assets/venues/venue-13/photo-2.webp",
      "seed-assets/venues/venue-13/photo-3.webp",
      "seed-assets/venues/venue-13/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user3",
    "name": "Караоке «Кеш&Cash»",
    "description": "Караaoke «Кеш&Cash» на Андріївському спуску — караaoke-клуб з сценою, про-звуком і каталогом тисяч пісень. Працює з вівторка по неділю з вечора до ранку; окремі VIP-зони для компаній, бар з коктейлями до самого світанку.",
    "address": "м. Київ, вул. Андріївська, 11/7",
    "latitude": "50.461950",
    "longitude": "30.522810",
    "contacts": {},
    "workingHours": {
      "fri": "21:00-06:00",
      "mon": "21:00-06:00",
      "sat": "21:00-06:00",
      "sun": "21:00-06:00",
      "thu": "21:00-06:00",
      "tue": "21:00-06:00",
      "wed": "21:00-06:00",
    },
    "averageCheck": 700.0,
    "type": "club",
    "features": [
      "wifi",
      "vip",
      "live_music",
    ],
    "tags": [
      "cocktails",
      "karaoke",
      "dancing",
    ],
    "photos": [
      "seed-assets/venues/venue-14/photo-1.webp",
      "seed-assets/venues/venue-14/photo-2.webp",
      "seed-assets/venues/venue-14/photo-3.webp",
      "seed-assets/venues/venue-14/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
  {
    "owner": "user3",
    "name": "Паб «Union Jack»",
    "description": "Англійський паб «Union Jack» у центрі Хмельницького — широке пивне меню, сидр, снеки та кухня гриль, трансляції футбольних матчів. Класичний пабовий інтерʼєр та барна стійка; вихідні — з гучним вечором до півночі.",
    "address": "м. Хмельницький, вул. Проскурівська, 16",
    "latitude": "49.425480",
    "longitude": "26.982050",
    "contacts": {
      "phone": "+380673805815",
    },
    "workingHours": {
      "fri": "11:00-24:00",
      "mon": "11:00-23:00",
      "sat": "11:00-24:00",
      "sun": "11:00-23:00",
      "thu": "11:00-23:00",
      "tue": "11:00-23:00",
      "wed": "11:00-23:00",
    },
    "averageCheck": 300.0,
    "type": "bar",
    "features": [
      "parking",
      "wifi",
      "live_music",
    ],
    "tags": [
      "food",
      "beer",
      "sports",
    ],
    "photos": [
      "seed-assets/venues/venue-15/photo-1.webp",
      "seed-assets/venues/venue-15/photo-2.webp",
      "seed-assets/venues/venue-15/photo-3.webp",
      "seed-assets/venues/venue-15/photo-4.webp",
    ],
    "mainPhotoIdx": 0,
  },
];
